import { useState } from 'react';
import { useGame } from '../../context/GameContext';
import { sendAction } from '../../api/client';
import { PremiumButton, PremiumCard, PremiumText } from '../../components/shared/PremiumComponents';
import { Scale, ShieldCheck, Skull, HeartHandshake, Zap } from 'lucide-react';
import { motion } from 'framer-motion';
import { PremiumGameLayout } from '../PremiumGameLayout';

export const AlignmentGameView = () => {
    const { gameState, sessionId, userId, updateGameState, gameSlug } = useGame();
    const [loading, setLoading] = useState(false);

    // Scenario data
    const scenario = gameState.last_ai_response?.scenario || "A merchant is caught stealing bread to feed his starving family. The law demands his hand, but mercy tugs at your heart.";
    const question = gameState.last_ai_response?.analysis || "What is your judgment?";
    const alignment = gameState.last_ai_response?.alignment_score || { law: 50, good: 50 }; // Hypothetical format

    const handleChoice = async (choice: string) => {
        if (!sessionId || !gameSlug) return;
        setLoading(true);
        try {
            const resp = await sendAction(gameSlug, sessionId, userId, 'choice', choice);
            if (resp.ok) updateGameState(resp.state);
        } catch (e) { console.error(e); }
        setLoading(false);
    };

    return (
        <PremiumGameLayout
            title="The Alignment Game"
            subtitle="Moral Compass"
            icon={Scale}
            backgroundVar="starfield"
            guideText="1. Face difficult moral dilemmas generated by the AI.\n2. Your choices shift your alignment across Law vs Chaos and Good vs Evil.\n3. Compare your final moral standing with other participants.\n4. Every decision shapes your digital soul."
        >
            <div className="h-full grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                {/* Left: The Scales (Visual) */}
                <div className="order-2 md:order-1 flex flex-col items-center justify-center relative">
                    <div className="absolute inset-0 bg-gold/5 blur-[100px] rounded-full" />

                    <div className="w-full max-w-sm space-y-8 relative z-10 p-8 bg-black/40 backdrop-blur-xl border border-white/5 rounded-3xl">
                        <div className="text-center mb-6">
                            <Scale size={48} className="text-gold mx-auto mb-2 opacity-80" />
                            <h3 className="text-white font-premium tracking-wider text-sm">CURRENT ALIGNMENT</h3>
                        </div>

                        {/* Visual Axis Bars */}
                        <div className="space-y-6">
                            <div>
                                <div className="flex justify-between text-[10px] uppercase tracking-widest text-gray-400 mb-2 font-bold">
                                    <span className="text-red-400">Chaos</span>
                                    <span className="text-blue-400">Order</span>
                                </div>
                                <div className="h-3 bg-white/5 rounded-full overflow-hidden border border-white/5 relative">
                                    <motion.div
                                        className="h-full bg-gradient-to-r from-red-500 via-purple-500 to-blue-500"
                                        initial={{ width: '50%' }}
                                        animate={{ width: `${alignment.law || 50}%` }}
                                        transition={{ duration: 1, ease: 'easeOut' }}
                                    />
                                    <div className="absolute top-0 bottom-0 left-1/2 w-[1px] bg-white/20" />
                                </div>
                            </div>
                            <div>
                                <div className="flex justify-between text-[10px] uppercase tracking-widest text-gray-400 mb-2 font-bold">
                                    <span className="text-red-500">Evil</span>
                                    <span className="text-green-500">Good</span>
                                </div>
                                <div className="h-3 bg-white/5 rounded-full overflow-hidden border border-white/5 relative">
                                    <motion.div
                                        className="h-full bg-gradient-to-r from-red-600 via-orange-500 to-green-500"
                                        initial={{ width: '50%' }}
                                        animate={{ width: `${alignment.good || 50}%` }}
                                        transition={{ duration: 1, ease: 'easeOut' }}
                                    />
                                    <div className="absolute top-0 bottom-0 left-1/2 w-[1px] bg-white/20" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Right: The Dilemma */}
                <div className="order-1 md:order-2 flex flex-col gap-6 h-full justify-center">
                    <div className="bg-white/5 p-8 rounded-3xl border border-white/5 shadow-2xl relative overflow-hidden group hover:border-gold/20 transition-colors">
                        <div className="absolute top-0 left-0 w-1 h-full bg-gold/50" />
                        <h2 className="text-xs font-bold text-gold mb-4 uppercase tracking-[0.2em] flex items-center gap-2">
                            <Zap size={12} /> Judgment Required
                        </h2>
                        <div className="text-xl md:text-2xl text-gray-100 leading-relaxed font-serif">
                            <PremiumText text={scenario} />
                        </div>
                        <p className="mt-6 text-sm text-gray-400 italic border-t border-white/5 pt-4">{question}</p>
                    </div>

                    <div className="grid grid-cols-1 gap-3">
                        {['Uphold the Law (Order)', 'Act with Mercy (Good)', 'Exploit Situation (Evil)', 'Create Chaos (Chaos)'].map((c, i) => (
                            <PremiumButton
                                key={c}
                                variant="secondary"
                                className="w-full text-left justify-between hover:bg-white/10 hover:border-gold/50 py-4 px-6 group transition-all"
                                onClick={() => handleChoice(c)}
                                disabled={loading}
                            >
                                <span className="text-gray-300 group-hover:text-white transition-colors">{c}</span>
                                {i === 0 && <ShieldCheck size={16} className="text-blue-400 opacity-50 group-hover:opacity-100" />}
                                {i === 1 && <HeartHandshake size={16} className="text-green-400 opacity-50 group-hover:opacity-100" />}
                                {i === 2 && <Skull size={16} className="text-red-400 opacity-50 group-hover:opacity-100" />}
                                {i === 3 && <Zap size={16} className="text-yellow-400 opacity-50 group-hover:opacity-100" />}
                            </PremiumButton>
                        ))}
                    </div>
                </div>
            </div>
        </PremiumGameLayout>
    );
};
