import { useState } from 'react';
import { useGame } from '../../context/GameContext';
import { sendAction } from '../../api/client';
import { PremiumButton, PremiumText } from '../../components/shared/PremiumComponents';
import { Book, Sparkles, Send, Feather } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { PremiumGameLayout } from '../PremiumGameLayout';

export const StoryWeaverView = () => {
    const { gameState, sessionId, userId, updateGameState, gameSlug, players } = useGame();
    const [input, setInput] = useState("");
    const [loading, setLoading] = useState(false);

    const narrative = gameState.last_ai_response?.narrative || (gameState.story_text && gameState.story_text.length > 0 ? gameState.story_text[gameState.story_text.length - 1] : "The page is empty. The ink waits for your imagination.");
    const phase = gameState.last_ai_response?.phase || gameState.phase || "Prologue";
    const visualCue = gameState.last_ai_response?.visual_cue || "Old Parchment";

    const handleContribute = async () => {
        if (!input.trim() || !sessionId || !gameSlug) return;
        setLoading(true);
        try {
            const resp = await sendAction(gameSlug, sessionId, userId, 'contribute', input);
            if (resp.ok) updateGameState(resp.state);
        } catch (e) { console.error(e); }
        setLoading(false);
        setInput("");
    };

    const playerOrder = gameState.player_order || [];
    const turnIndex = gameState.turn_index || 0;
    const currentTurnUserId = playerOrder.length > 0 ? playerOrder[turnIndex % playerOrder.length] : null;
    const isMyTurn = !currentTurnUserId || currentTurnUserId === userId;

    // Get name of current turn player
    const currentTurnParams = players[currentTurnUserId] || {};
    // Extract name from params or fallback
    const currentTurnName = currentTurnParams.name || (currentTurnUserId === userId ? "You" : "Another Weaver");

    return (
        <PremiumGameLayout
            title="The Story Weaver"
            subtitle={`Chapter: ${phase}`}
            icon={Book}
            backgroundVar="starfield"
            guideText="1. Read the current scene generated by the AI.\n2. Type how the hero Lysandra reacts or what she discovers.\n3. The AI Master will then weave your choice into the next chapter.\n4. Work with other Seekers to finish the quest!"
        >
            <div className="flex flex-col h-full relative">

                {/* Visual Cue Indicator */}
                <div className="absolute top-0 right-12 p-2 text-[10px] text-white/30 uppercase tracking-widest bg-black/20 rounded-bl-xl border-b border-l border-white/5 backdrop-blur-sm z-20">
                    <span className="flex items-center gap-1"><Feather size={10} /> {visualCue}</span>
                </div>

                {/* Turn Indicator */}
                <div className="absolute top-0 left-12 p-2 text-[10px] uppercase tracking-widest bg-black/20 rounded-br-xl border-b border-r border-white/5 backdrop-blur-sm z-20">
                    {isMyTurn ? (
                        <span className="text-green-400 font-bold animate-pulse">Your Turn</span>
                    ) : (
                        <span className="text-white/40">Waiting for {currentTurnName}...</span>
                    )}
                </div>


                {/* Main Content Area - The "Book" */}
                {/* Scrollable Story Panel */}
                <div className="relative flex-1 p-6 md:p-12 overflow-y-auto custom-scrollbar">
                    <div className="max-w-prose mx-auto">
                        <AnimatePresence mode='wait'>
                            <motion.div
                                key={narrative.substring(0, 20)} // Key changes trigger animation
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0 }}
                                transition={{ duration: 0.8, ease: "easeOut" }}
                                className="font-serif text-lg md:text-xl text-gray-200 leading-[2.2] tracking-wide first-letter:text-5xl first-letter:text-gold first-letter:font-bold first-letter:float-left first-letter:mr-3 first-letter:mt-[-5px]"
                            >
                                <PremiumText text={narrative} />
                            </motion.div>
                        </AnimatePresence>

                        {(gameState.story_text?.length > 1) && (
                            <div className="mt-12 pt-8 border-t border-white/5 text-center">
                                <span className="text-xs text-white/20 uppercase tracking-widest mb-4 block">Previous Chronicles</span>
                                <div className="text-sm text-gray-500 font-serif leading-relaxed line-clamp-3 hover:line-clamp-none transition-all cursor-pointer opacity-60 hover:opacity-100 italic">
                                    "...{gameState.story_text.slice(0, -1).join(" ")}..."
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Interaction Footer */}
                <div className="p-4 md:p-6 bg-black/40 border-t border-white/5 flex gap-4 items-end relative z-30">
                    <div className="flex-1 relative group">
                        <div className={`absolute -inset-0.5 bg-gradient-to-r from-gold/20 to-purple-500/20 rounded-xl transition duration-500 blur-sm ${isMyTurn ? 'opacity-100' : 'opacity-0'}`} />
                        <textarea
                            value={input}
                            onChange={e => setInput(e.target.value)}
                            onKeyDown={e => e.key === 'Enter' && !e.shiftKey && (e.preventDefault(), handleContribute())}
                            placeholder={isMyTurn ? "Weave your thread into the story..." : `Waiting for ${currentTurnName} to weave...`}
                            className={`relative w-full bg-[#151220] border rounded-xl px-4 py-3 min-h-[60px] max-h-[120px] text-gray-200 placeholder:text-gray-600 focus:outline-none resize-none scrollbar-hide font-serif text-lg transition-all ${isMyTurn ? 'border-white/10 focus:border-gold/30' : 'border-white/5 opacity-50 cursor-not-allowed'}`}
                            disabled={loading || !isMyTurn}
                        />
                        {isMyTurn && (
                            <div className="absolute bottom-2 right-2 text-[10px] text-white/20 pointer-events-none">
                                SHIFT+ENTER for new line
                            </div>
                        )}
                    </div>
                    <PremiumButton
                        onClick={handleContribute}
                        disabled={loading || !input || !isMyTurn}
                        className={`h-[60px] px-6 ${loading || !isMyTurn ? 'opacity-50 grayscale' : ''}`}
                    >
                        {loading ? (
                            <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1 }} >
                                <Sparkles size={20} />
                            </motion.div>
                        ) : (
                            <Send size={20} />
                        )}
                    </PremiumButton>
                </div>
            </div>
        </PremiumGameLayout>
    );
};
