"""Add multiplayer columns to game_sessions

Revision ID: 42b34864db48
Revises: ef1234567890
Create Date: 2025-12-27 19:22:20.899836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42b34864db48'
down_revision: Union[str, None] = 'ef1234567890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_results')
    op.drop_table('social_posts')
    op.drop_table('social_interactions')
    op.drop_table('service_keys')
    op.drop_table('rituals')
    op.drop_table('moodboards')
    op.drop_table('events')
    op.drop_table('plans')
    op.drop_table('rate_limit_logs')
    op.drop_table('api_usage_logs')
    op.drop_table('quizzes')
    op.drop_table('nudges')
    op.drop_table('credit_purchases')
    op.drop_table('transactions')
    op.drop_table('photo_journals')
    op.add_column('game_sessions', sa.Column('room_code', sa.String(length=10), nullable=True))
    op.add_column('game_sessions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('game_sessions', sa.Column('max_players', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('analysis', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_game_sessions_room_code'), 'game_sessions', ['room_code'], unique=True)
    op.add_column('reports', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('reports', 'reporter_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reports', 'reported_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reports', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'reports', 'tenants', ['reporter_id'], ['id'])
    op.alter_column('subscriptions', 'tenant',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'subscriptions', 'tenants', ['tenant'], ['id'])
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tenants', 'declined_users',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tenants', 'archived_connections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'archived_connections',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tenants', 'declined_users',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tenants', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.alter_column('subscriptions', 'tenant',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reports', 'reported_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reports', 'reporter_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('reports', 'description')
    op.drop_index(op.f('ix_game_sessions_room_code'), table_name='game_sessions')
    op.drop_column('game_sessions', 'analysis')
    op.drop_column('game_sessions', 'max_players')
    op.drop_column('game_sessions', 'status')
    op.drop_column('game_sessions', 'room_code')
    op.create_table('photo_journals',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('caption', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant'], ['tenants.id'], name=op.f('photo_journals_tenant_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_journals_pkey'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscription', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits_purchased', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='transactionstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_table('credit_purchases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits_purchased', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='transactionstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_purchases_pkey')),
    sa.UniqueConstraint('transaction_id', name=op.f('credit_purchases_transaction_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('nudges',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant'], ['tenants.id'], name=op.f('nudges_tenant_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('nudges_pkey'))
    )
    op.create_table('quizzes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tenants.id'], name='quizzes_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='quizzes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('api_usage_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscription', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('credits_consumed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_usage_logs_pkey'))
    )
    op.create_table('rate_limit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requests_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('window_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rate_limit_logs_pkey'))
    )
    op.create_table('plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('plan_type', postgresql.ENUM('FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE', name='plantype'), autoincrement=False, nullable=False),
    sa.Column('price_monthly', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_yearly', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('credits_included', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_requests_per_minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_requests_per_hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_requests_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('plans_pkey')),
    sa.UniqueConstraint('name', name=op.f('plans_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attendees', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['tenants.id'], name=op.f('events_host_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_table('moodboards',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant'], ['tenants.id'], name=op.f('moodboards_tenant_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('moodboards_pkey'))
    )
    op.create_table('rituals',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('streak_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant'], ['tenants.id'], name=op.f('rituals_tenant_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rituals_pkey'))
    )
    op.create_table('service_keys',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('key_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('service_keys_pkey'))
    )
    op.create_table('social_interactions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tenants.id'], name=op.f('social_interactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('social_interactions_pkey'))
    )
    op.create_table('social_posts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('media_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('likes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('comments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['tenants.id'], name=op.f('social_posts_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('social_posts_pkey'))
    )
    op.create_table('quiz_results',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_results_quiz_id_fkey')),
    sa.ForeignKeyConstraint(['tenant'], ['tenants.id'], name=op.f('quiz_results_tenant_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_results_pkey'))
    )
    # ### end Alembic commands ###
