[
  {
    "id": "q001",
    "text": "What moment from childhood still makes you smile when you think about it?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_001.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "private"
  },
  {
    "id": "q002",
    "text": "Describe a perfect weekend with someone you care about — where are you and what are you doing?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_002.jpg",
    "liked": false,
    "tags": ["relationship", "friends"],
    "visibility": "private"
  },
  {
    "id": "q003",
    "text": "What's a tiny ritual that makes your day better, and why does it matter?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_003.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "private"
  },
  {
    "id": "q004",
    "text": "Name a book or film that changed how you see the world — what did it teach you?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_004.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q005",
    "text": "Share a small kindness someone did for you that you still remember.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_005.jpg",
    "liked": false,
    "tags": ["relationships", "family", "friends"],
    "visibility": "private"
  },
  {
    "id": "q006",
    "text": "If you could design a ritual to strengthen a relationship, what would it include?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_006.jpg",
    "liked": false,
    "tags": ["relationship", "games and activities"],
    "visibility": "private"
  },
  {
    "id": "q007",
    "text": "What's one hobby you've always wanted to try but haven't yet?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_007.jpg",
    "liked": false,
    "tags": ["leisure", "misc", "self"],
    "visibility": "public"
  },
  {
    "id": "q008",
    "text": "Tell a story about the strangest compliment you've ever received.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_008.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "private"
  },
  {
    "id": "q009",
    "text": "What value do you refuse to compromise on in relationships?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_009.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "public"
  },
  {
    "id": "q010",
    "text": "Share a family tradition you love and why it matters.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_010.jpg",
    "liked": false,
    "tags": ["family", "general"],
    "visibility": "private"
  },
  {
    "id": "q011",
    "text": "What's a small adventure you can do this week with a friend or partner?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_011.jpg",
    "liked": false,
    "tags": ["friends", "games and activities"],
    "visibility": "private"
  },
  {
    "id": "q012",
    "text": "When do you feel most like yourself? Describe that moment.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_012.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q013",
    "text": "If you could ask a partner one question to understand them deeply, what would it be?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_013.jpg",
    "liked": false,
    "tags": ["relationship", "misc"],
    "visibility": "private"
  },
  {
    "id": "q014",
    "text": "Name a small habit you’d like to build together with someone else.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_014.jpg",
    "liked": false,
    "tags": ["relationship", "games and activities"],
    "visibility": "private"
  },
  {
    "id": "q015",
    "text": "Describe an unexpected place where you felt deeply connected to others.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_015.jpg",
    "liked": false,
    "tags": ["friends", "family", "general"],
    "visibility": "public"
  },
  {
    "id": "q016",
    "text": "What does 'being supportive' mean to you in practice?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_016.jpg",
    "liked": false,
    "tags": ["relationship", "family"],
    "visibility": "private"
  },
  {
    "id": "q017",
    "text": "Tell about a time you changed your mind about something important.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_017.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q018",
    "text": "What's a simple game or activity you love to play with others?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_018.jpg",
    "liked": false,
    "tags": ["games and activities", "friends"],
    "visibility": "private"
  },
  {
    "id": "q019",
    "text": "If you had to pick a shared goal with someone, what would it be?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_019.jpg",
    "liked": false,
    "tags": ["relationship", "collaboration", "misc"],
    "visibility": "private"
  },
  {
    "id": "q020",
    "text": "What family story do you love telling at gatherings?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_020.jpg",
    "liked": false,
    "tags": ["family", "general"],
    "visibility": "public"
  },
  {
    "id": "q021",
    "text": "Name one fear you’ve overcome and how you did it.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_021.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "private"
  },
  {
    "id": "q022",
    "text": "What is a small, cheap thing that always makes you feel cared for?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_022.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "private"
  },
  {
    "id": "q023",
    "text": "Share a habit you admire in someone else and want to try yourself.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_023.jpg",
    "liked": false,
    "tags": ["self", "friends"],
    "visibility": "public"
  },
  {
    "id": "q024",
    "text": "Describe a memorable meal and the people who made it special.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_024.jpg",
    "liked": false,
    "tags": ["family", "friends", "general"],
    "visibility": "private"
  },
  {
    "id": "q025",
    "text": "If you could spend an afternoon teaching someone one skill, what would it be?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_025.jpg",
    "liked": false,
    "tags": ["games and activities", "collaboration"],
    "visibility": "public"
  },
  {
    "id": "q026",
    "text": "What small disagreement taught you something valuable about communicating?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_026.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "private"
  },
  {
    "id": "q027",
    "text": "Share a secret place in your city that you love to hide away in.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_027.jpg",
    "liked": false,
    "tags": ["general", "friends"],
    "visibility": "public"
  },
  {
    "id": "q028",
    "text": "What's one small generosity you try to practice regularly?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_028.jpg",
    "liked": false,
    "tags": ["self", "family"],
    "visibility": "private"
  },
  {
    "id": "q029",
    "text": "If you lined up three songs that define a phase of your life, what would they be?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_029.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q030",
    "text": "Describe a time you felt proud to be part of a group.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_030.jpg",
    "liked": false,
    "tags": ["friends", "family"],
    "visibility": "private"
  },
  {
    "id": "q031",
    "text": "What's a playful dare you would give a partner or friend?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_031.jpg",
    "liked": false,
    "tags": ["games and activities", "friends"],
    "visibility": "private"
  },
  {
    "id": "q032",
    "text": "Which small daily decision reveals your priorities most clearly?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_032.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q033",
    "text": "Tell about someone who taught you how to be kinder.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_033.jpg",
    "liked": false,
    "tags": ["family", "relationship"],
    "visibility": "private"
  },
  {
    "id": "q034",
    "text": "What's one thing you'd like to celebrate with your friends this year?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_034.jpg",
    "liked": false,
    "tags": ["friends", "general"],
    "visibility": "public"
  },
  {
    "id": "q035",
    "text": "Imagine a quiet ritual you and a partner could do every month — what is it?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_035.jpg",
    "liked": false,
    "tags": ["relationship", "games and activities"],
    "visibility": "private"
  },
  {
    "id": "q036",
    "text": "What small gesture makes you feel truly listened to?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_036.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "private"
  },
  {
    "id": "q037",
    "text": "Describe a creative project you'd love to start with a friend.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_037.jpg",
    "liked": false,
    "tags": ["collaboration", "games and activities"],
    "visibility": "public"
  },
  {
    "id": "q038",
    "text": "What's the funniest misunderstanding you've had with family or friends?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_038.jpg",
    "liked": false,
    "tags": ["family", "friends"],
    "visibility": "private"
  },
  {
    "id": "q039",
    "text": "When did someone forgive you in a way that surprised you?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_039.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "public"
  },
  {
    "id": "q040",
    "text": "If you were planning a spontaneous day out, what would be on the itinerary?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_040.jpg",
    "liked": false,
    "tags": ["friends", "games and activities"],
    "visibility": "private"
  },
  {
    "id": "q041",
    "text": "What small chance encounter changed your perspective on something?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_041.jpg",
    "liked": false,
    "tags": ["general", "self"],
    "visibility": "public"
  },
  {
    "id": "q042",
    "text": "Share a memory where silence felt comfortable and meaningful.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_042.jpg",
    "liked": false,
    "tags": ["relationship", "friends"],
    "visibility": "private"
  },
  {
    "id": "q043",
    "text": "What household task do you secretly find soothing?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_043.jpg",
    "liked": false,
    "tags": ["self", "relationship"],
    "visibility": "public"
  },
  {
    "id": "q044",
    "text": "Name a small tradition you'd like to start with your chosen circle.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_044.jpg",
    "liked": false,
    "tags": ["friends", "family", "games and activities"],
    "visibility": "private"
  },
  {
    "id": "q045",
    "text": "What's one question you wish people asked you more often?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_045.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q046",
    "text": "Describe a time you had to apologize — what did you learn?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_046.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "private"
  },
  {
    "id": "q047",
    "text": "If you could create a theme night with friends, what would it be?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_047.jpg",
    "liked": false,
    "tags": ["games and activities", "friends"],
    "visibility": "private"
  },
  {
    "id": "q048",
    "text": "What small thing do you do to recharge after a hard day?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_048.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q049",
    "text": "Share a quote or line of poetry that feels like part of your life story.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_049.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "private"
  },
  {
    "id": "q050",
    "text": "What's an awkward habit you secretly adore in someone else?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_050.jpg",
    "liked": false,
    "tags": ["relationship", "friends"],
    "visibility": "public"
  },
  {
    "id": "q051",
    "text": "If you had a shared playlist for a relationship or friendship, what would the opening song be?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_051.jpg",
    "liked": false,
    "tags": ["relationship", "friends"],
    "visibility": "private"
  },
  {
    "id": "q052",
    "text": "What's one small boundary that helps you feel safe with others?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_052.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "public"
  },
  {
    "id": "q053",
    "text": "Describe a weekend project you’d love to do with a friend.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_053.jpg",
    "liked": false,
    "tags": ["games and activities", "collaboration"],
    "visibility": "private"
  },
  {
    "id": "q054",
    "text": "When was the last time you changed a long-held habit? What prompted it?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_054.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q055",
    "text": "What silly challenge would you give to your friend group for a weekend?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_055.jpg",
    "liked": false,
    "tags": ["games and activities", "friends"],
    "visibility": "private"
  },
  {
    "id": "q056",
    "text": "Share a small object that means a lot to you and why.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_056.jpg",
    "liked": false,
    "tags": ["self", "family"],
    "visibility": "public"
  },
  {
    "id": "q057",
    "text": "What's a personal rule you live by when it comes to trust?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_057.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "private"
  },
  {
    "id": "q058",
    "text": "If you could host a one-hour salon, what topic would you pick and who would you invite?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_058.jpg",
    "liked": false,
    "tags": ["friends", "collaboration"],
    "visibility": "public"
  },
  {
    "id": "q059",
    "text": "Tell about a time you created something with someone that you both loved.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_059.jpg",
    "liked": false,
    "tags": ["collaboration", "friends"],
    "visibility": "private"
  },
  {
    "id": "q060",
    "text": "What's one small act of courage you'd like to take in relationships this year?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_060.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "public"
  },
  {
    "id": "q061",
    "text": "Describe a time you felt surprised by someone’s generosity.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_061.jpg",
    "liked": false,
    "tags": ["family", "friends"],
    "visibility": "private"
  },
  {
    "id": "q062",
    "text": "Name one personal value you want your close circle to share.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_062.jpg",
    "liked": false,
    "tags": ["self", "friends"],
    "visibility": "public"
  },
  {
    "id": "q063",
    "text": "If you could build a tiny tradition for the holidays, what would it be?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_063.jpg",
    "liked": false,
    "tags": ["family", "games and activities"],
    "visibility": "private"
  },
  {
    "id": "q064",
    "text": "What's one question that reveals someone's curiosity to you?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_064.jpg",
    "liked": false,
    "tags": ["self", "relationship"],
    "visibility": "public"
  },
  {
    "id": "q065",
    "text": "Share a memory where a mistake turned into something beautiful.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_065.jpg",
    "liked": false,
    "tags": ["general", "friends"],
    "visibility": "private"
  },
  {
    "id": "q066",
    "text": "What hobby would you teach to a visiting friend and why?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_066.jpg",
    "liked": false,
    "tags": ["games and activities", "friends"],
    "visibility": "public"
  },
  {
    "id": "q067",
    "text": "Describe a boundary you set that improved a relationship.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_067.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "private"
  },
  {
    "id": "q068",
    "text": "Tell a short story about an unexpected friendship and how it started.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_068.jpg",
    "liked": false,
    "tags": ["friends", "general"],
    "visibility": "public"
  },
  {
    "id": "q069",
    "text": "What is a tiny creative prompt you’d give someone to spark conversation?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_069.jpg",
    "liked": false,
    "tags": ["games and activities", "misc"],
    "visibility": "private"
  },
  {
    "id": "q070",
    "text": "If you could relive one weekend, which would it be and why?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_070.jpg",
    "liked": false,
    "tags": ["general", "friends"],
    "visibility": "public"
  },
  {
    "id": "q071",
    "text": "What's a small kindness you wish people knew how to offer better?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_071.jpg",
    "liked": false,
    "tags": ["relationship", "family"],
    "visibility": "private"
  },
  {
    "id": "q072",
    "text": "Share a quirky tradition your family has that outsiders find odd.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_072.jpg",
    "liked": false,
    "tags": ["family", "misc"],
    "visibility": "public"
  },
  {
    "id": "q073",
    "text": "Describe a time you and someone solved a problem together creatively.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_073.jpg",
    "liked": false,
    "tags": ["collaboration", "friends"],
    "visibility": "private"
  },
  {
    "id": "q074",
    "text": "If you had to explain your life philosophy in one sentence, what would it be?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_074.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q075",
    "text": "What's a memory that still surprises you when you think about it?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_075.jpg",
    "liked": false,
    "tags": ["self", "friends"],
    "visibility": "private"
  },
  {
    "id": "q076",
    "text": "Name a small skill you'd like to learn together with someone else.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_076.jpg",
    "liked": false,
    "tags": ["games and activities", "collaboration"],
    "visibility": "public"
  },
  {
    "id": "q077",
    "text": "Tell about a time you were pleasantly surprised by someone's vulnerability.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_077.jpg",
    "liked": false,
    "tags": ["relationship", "friends"],
    "visibility": "private"
  },
  {
    "id": "q078",
    "text": "What small environmental change in your life made the biggest difference?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_078.jpg",
    "liked": false,
    "tags": ["self", "misc"],
    "visibility": "public"
  },
  {
    "id": "q079",
    "text": "Describe a shared accomplishment you want to celebrate with someone.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_079.jpg",
    "liked": false,
    "tags": ["friends", "collaboration"],
    "visibility": "private"
  },
  {
    "id": "q080",
    "text": "What's a comfort food that connects you to home or family?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_080.jpg",
    "liked": false,
    "tags": ["family", "self"],
    "visibility": "public"
  },
  {
    "id": "q081",
    "text": "If you could trade lives with a friend for a day, who and why?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_081.jpg",
    "liked": false,
    "tags": ["friends", "general"],
    "visibility": "private"
  },
  {
    "id": "q082",
    "text": "Share a question you think everyone should ask themselves occasionally.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_082.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "public"
  },
  {
    "id": "q083",
    "text": "What's a playful way to check in emotionally with someone you love?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_083.jpg",
    "liked": false,
    "tags": ["relationship", "games and activities"],
    "visibility": "private"
  },
  {
    "id": "q084",
    "text": "Describe a lesson you learned from a disagreement with a friend.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_084.jpg",
    "liked": false,
    "tags": ["friends", "self"],
    "visibility": "public"
  },
  {
    "id": "q085",
    "text": "If you could give your younger self one piece of advice about relationships, what would it be?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_085.jpg",
    "liked": false,
    "tags": ["relationship", "self"],
    "visibility": "private"
  },
  {
    "id": "q086",
    "text": "What's a small community or group you wish existed where you live?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_086.jpg",
    "liked": false,
    "tags": ["friends", "collaboration"],
    "visibility": "public"
  },
  {
    "id": "q087",
    "text": "Share a habit you once thought silly but now appreciate.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_087.jpg",
    "liked": false,
    "tags": ["self", "general"],
    "visibility": "private"
  },
  {
    "id": "q088",
    "text": "Describe a creative compromise that improved a partnership or project.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_088.jpg",
    "liked": false,
    "tags": ["collaboration", "relationship"],
    "visibility": "public"
  },
  {
    "id": "q089",
    "text": "What's a question that always sparks good conversation at dinner?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_089.jpg",
    "liked": false,
    "tags": ["games and activities", "general"],
    "visibility": "private"
  },
  {
    "id": "q090",
    "text": "Tell about a small travel memory that shaped your taste for adventure.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_090.jpg",
    "liked": false,
    "tags": ["general", "friends"],
    "visibility": "public"
  },
  {
    "id": "q091",
    "text": "What everyday routine do you appreciate most in a partner or friend?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_091.jpg",
    "liked": false,
    "tags": ["relationship", "friends"],
    "visibility": "private"
  },
  {
    "id": "q092",
    "text": "Share a time you collaborated and discovered each other's hidden strengths.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_092.jpg",
    "liked": false,
    "tags": ["collaboration", "friends"],
    "visibility": "public"
  },
  {
    "id": "q093",
    "text": "What's a small way you like to mark progress or milestones?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_093.jpg",
    "liked": false,
    "tags": ["self", "collaboration"],
    "visibility": "private"
  },
  {
    "id": "q094",
    "text": "If you could invent a new holiday about connection, what would people do?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_094.jpg",
    "liked": false,
    "tags": ["games and activities", "family"],
    "visibility": "public"
  },
  {
    "id": "q095",
    "text": "Describe a moment when a friend helped you see your blind spot.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_095.jpg",
    "liked": false,
    "tags": ["friends", "self"],
    "visibility": "private"
  },
  {
    "id": "q096",
    "text": "What small creative constraint would you impose to make a project more fun?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_096.jpg",
    "liked": false,
    "tags": ["games and activities", "collaboration"],
    "visibility": "public"
  },
  {
    "id": "q097",
    "text": "Share a time you felt truly at home with someone new.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_097.jpg",
    "liked": false,
    "tags": ["relationship", "friends"],
    "visibility": "private"
  },
  {
    "id": "q098",
    "text": "What's one habit you want to pass on to the next generation?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_098.jpg",
    "liked": false,
    "tags": ["family", "self"],
    "visibility": "public"
  },
  {
    "id": "q099",
    "text": "Describe a small experiment you'd run to make your community kinder.",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_099.jpg",
    "liked": false,
    "tags": ["collaboration", "misc"],
    "visibility": "private"
  },
  {
    "id": "q100",
    "text": "What's a closing question you'd like to ask someone after a deep conversation?",
    "meta_note": "",
    "favourite": false,
    "shown": false,
    "image": "images/card_100.jpg",
    "liked": false,
    "tags": ["relationship", "general"],
    "visibility": "public"
  }
]




[
  {"id":"q001","text":"What small, ordinary thing always makes your day better?","tags":["self","general","fun"],"meta_note":"Good warm-up; invites sensory detail."},
  {"id":"q002","text":"Describe a time you felt unexpectedly proud of yourself.","tags":["self","deep"],"meta_note":"Encourages vulnerability without heavy risk."},
  {"id":"q003","text":"What’s a childhood routine you secretly miss?","tags":["self","family","nostalgia"],"meta_note":"Works well with family audiences."},
  {"id":"q004","text":"If we had 24 hours with no responsibilities, what would your perfect day look like?","tags":["relationship","friends","fun"],"meta_note":"Great for planning real or fantasy dates."},
  {"id":"q005","text":"What is a tiny ritual you’d like to build with a partner?","tags":["relationship","rituals"],"meta_note":"Leads to practical, repeatable ideas."},
  {"id":"q006","text":"Which book or film altered your worldview the most, and why?","tags":["self","intellectual"],"meta_note":"Deep dive starter; follow with favorite passage."},
  {"id":"q007","text":"Tell the story of the best meal you ever shared with someone.","tags":["friends","family","sensory"],"meta_note":"Evokes atmosphere and social warmth."},
  {"id":"q008","text":"What hobby have you tried and given up—what did you learn?","tags":["self","learning"],"meta_note":"Promotes humility and growth stories."},
  {"id":"q009","text":"Name one habit you want to keep for the rest of your life.","tags":["self","goals"],"meta_note":"Good for values and long-term thinking."},
  {"id":"q010","text":"What’s a compliment you’ll never forget?","tags":["self","relationship"],"meta_note":"Signals what people value hearing."},
  {"id":"q011","text":"If you could bring one obsolete skill back into daily life, what would it be?","tags":["intellectual","misc"],"meta_note":"Fun history/skills exploration."},
  {"id":"q012","text":"Describe a place that feels like home to you, even if it isn’t where you live.","tags":["self","nostalgia"],"meta_note":"Use imagery prompts for vivid answers."},
  {"id":"q013","text":"What’s an odd fear you have that most people wouldn’t guess?","tags":["self","quirky"],"meta_note":"Light vulnerability—best with trust."},
  {"id":"q014","text":"If you wrote a letter to your future partner, what would the first sentence say?","tags":["relationship","writing"],"meta_note":"Great for reflective dating prompts."},
  {"id":"q015","text":"Pick three songs that define a chapter of your life and explain why.","tags":["self","music","story"],"meta_note":"Works great with shared playlists."},
  {"id":"q016","text":"Tell about someone who showed you a different way to be in the world.","tags":["deep","self"],"meta_note":"Invites acknowledgements and gratitude."},
  {"id":"q017","text":"What small community ritual would you start in your neighborhood if you could?","tags":["collaboration","community"],"meta_note":"Sparks civic imagination."},
  {"id":"q018","text":"If you had to explain your job to a 10-year-old, how would you do it?","tags":["collaboration","fun"],"meta_note":"Great for clarity and humour."},
  {"id":"q019","text":"What’s a question you wish people asked you more often?","tags":["self","relationship"],"meta_note":"Reveals inner priorities."},
  {"id":"q020","text":"Describe a tiny kindness you remember from someone you barely knew.","tags":["friends","family"],"meta_note":"Powerful for empathy-building."},
  {"id":"q021","text":"If your life had a theme song right now, what would it be?","tags":["self","fun"],"meta_note":"Quick mood-check and icebreaker."},
  {"id":"q022","text":"What was the first moment you realized you were different from your parents?","tags":["family","identity"],"meta_note":"Deeper family dynamics; use with care."},
  {"id":"q023","text":"If you could design a weekend ritual to recharge, what would it include?","tags":["self","rituals"],"meta_note":"Practical and immediately actionable."},
  {"id":"q024","text":"Tell a story about a time you made a friend in an unexpected place.","tags":["friends","story"],"meta_note":"Great for travel and serendipity tales."},
  {"id":"q025","text":"What’s a small tradition your family has that you’d like to keep or change?","tags":["family","tradition"],"meta_note":"Promotes generational reflection."},
  {"id":"q026","text":"If you had to describe your sense of humour in three words, what would they be?","tags":["self","fun"],"meta_note":"Quick personality snapshot."},
  {"id":"q027","text":"Name an idea you once strongly believed but now question.","tags":["intellectual","self"],"meta_note":"Shows intellectual humility."},
  {"id":"q028","text":"What’s a harmless lie you tell to make social life easier?","tags":["quirky","friends"],"meta_note":"Playful, best with trusted groups."},
  {"id":"q029","text":"If you could invite one historical figure to dinner, who and what would you ask?","tags":["intellectual","thought-experiment"],"meta_note":"Leads to values and curiosity talk."},
  {"id":"q030","text":"What small design change would make your city instantly better?","tags":["collaboration","community"],"meta_note":"Idea generation for local impact."},
  {"id":"q031","text":"Describe a sensory memory that always grounds you.","tags":["self","mindfulness"],"meta_note":"Use to practice grounding and presence."},
  {"id":"q032","text":"What's a risk you took that ended up reshaping your life?","tags":["deep","self"],"meta_note":"Encourages storytelling about turning points."},
  {"id":"q033","text":"If you could invent a new holiday about connection, what would people do?","tags":["games","community"],"meta_note":"Creative group brainstorming prompt."},
  {"id":"q034","text":"What fictional character do you secretly identify with and why?","tags":["self","story"],"meta_note":"Reveals inner archetypes."},
  {"id":"q035","text":"Tell me about a time you changed your mind because of someone else's bravery.","tags":["deep","friends"],"meta_note":"Highlights influence and moral growth."},
  {"id":"q036","text":"If you could master any craft in six months, which would you choose?","tags":["self","skills"],"meta_note":"Good for goal-setting and curiosity."},
  {"id":"q037","text":"What’s the smallest compliment that has ever had the biggest effect on you?","tags":["relationship","self"],"meta_note":"Shows how micro-moments matter."},
  {"id":"q038","text":"Describe a book you’d give to someone to change their weekend.","tags":["friends","recommendation"],"meta_note":"Shareable cultural exchange."},
  {"id":"q039","text":"What item in your room tells the most interesting story about you?","tags":["self","nostalgia"],"meta_note":"Leads to physical storytelling."},
  {"id":"q040","text":"If you had to build a team to solve a neighborhood problem, who would you recruit and why?","tags":["collaboration","community"],"meta_note":"Explores roles and values."},
  {"id":"q041","text":"What’s an experience that made you kinder to yourself?","tags":["self","growth"],"meta_note":"Encourages self-compassion."},
  {"id":"q042","text":"Share a small project you started and abandoned—what would you do differently now?","tags":["collaboration","learning"],"meta_note":"Low-stakes reflection on iteration."},
  {"id":"q043","text":"If you could live inside any era for a month, which would you pick and why?","tags":["thought-experiment","intellectual"],"meta_note":"Counterfactual historical imagination."},
  {"id":"q044","text":"Describe the last time you laughed until you cried.","tags":["friends","fun"],"meta_note":"Good for bonding and warmth."},
  {"id":"q045","text":"What question would you ask your teenage self if you could call them for five minutes?","tags":["self","advice"],"meta_note":"Reflective and tender prompt."},
  {"id":"q046","text":"Name a small everyday frustration you secretly enjoy solving.","tags":["quirky","self"],"meta_note":"Shows problem-solving personality."},
  {"id":"q047","text":"If you had to summarize your love style in one metaphor, what would it be?","tags":["relationship","creative"],"meta_note":"Poetic prompt for partners."},
  {"id":"q048","text":"Tell a brief story about someone who surprised you with generosity.","tags":["friends","family"],"meta_note":"Builds appreciation and trust."},
  {"id":"q049","text":"Which trivial skill makes you oddly confident?","tags":["fun","self"],"meta_note":"Playful ego-friendly prompt."},
  {"id":"q050","text":"If you could erase one minor social awkwardness from your past, which would you choose?","tags":["quirky","self"],"meta_note":"Lightly vulnerable and funny."},
  {"id":"q051","text":"What’s a counterfactual you like to imagine—what if you had chosen a different career?","tags":["counterfactual","intellectual"],"meta_note":"Encourages alternate-life storytelling."},
  {"id":"q052","text":"Describe a time you discovered a surprising shared interest with someone older or younger than you.","tags":["friends","family"],"meta_note":"Bridges generational gaps."},
  {"id":"q053","text":"What micro-habit has improved your relationships the most?","tags":["relationship","self"],"meta_note":"Practical and actionable."},
  {"id":"q054","text":"If you could teach a one-hour masterclass for free, what would you teach?","tags":["collaboration","skills"],"meta_note":"Reveals strengths and passions."},
  {"id":"q055","text":"Tell a short story of a time you failed fast and learned quicker.","tags":["work","growth"],"meta_note":"Startup-friendly narrative prompt."},
  {"id":"q056","text":"If you had to make a manifesto of three values, what would they be?","tags":["self","values"],"meta_note":"Concise values elicitation."},
  {"id":"q057","text":"What’s your favorite question to ask strangers to spark a great conversation?","tags":["friends","games"],"meta_note":"Meta-question for conversation designers."},
  {"id":"q058","text":"Describe a quiet place you go to recharge and what you do there.","tags":["self","mindfulness"],"meta_note":"Promotes restorative practices."},
  {"id":"q059","text":"If you could have one superpower for social situations, what would it be?","tags":["fun","quirky"],"meta_note":"Light imaginative prompt."},
  {"id":"q060","text":"What’s an ethical dilemma you think about often and why?","tags":["intellectual","deep"],"meta_note":"Good for thoughtful debate."},
  {"id":"q061","text":"Share a tiny change you made that had outsized impact on your wellbeing.","tags":["self","health"],"meta_note":"Encourages practical tips."},
  {"id":"q062","text":"Which meal would you choose for your last supper and who’s at the table?","tags":["family","friends","story"],"meta_note":"Invites intimacy and values."},
  {"id":"q063","text":"If you could invent a new word, what would it mean and how would people use it?","tags":["creative","fun"],"meta_note":"Language play and creativity."},
  {"id":"q064","text":"Tell about a time you were proud of someone else and why.","tags":["friends","family"],"meta_note":"Builds positive social currency."},
  {"id":"q065","text":"What’s a question you could ask today that would change the way you live tomorrow?","tags":["self","intellectual"],"meta_note":"Meta-reflective nudge for growth."},
  {"id":"q066","text":"Describe a personal boundary you struggled to set but now benefit from.","tags":["self","relationship"],"meta_note":"Encourages healthy communication."},
  {"id":"q067","text":"If you had to narrate your life as a movie genre, which genre fits and who plays the lead?","tags":["story","fun"],"meta_note":"Playful cinematic mapping."},
  {"id":"q068","text":"What’s the most useful unglamorous advice you’ve received?","tags":["self","wisdom"],"meta_note":"Shares practical life hacks."},
  {"id":"q069","text":"Share a time you collaborated with someone with radically different skills—what worked?","tags":["collaboration","learning"],"meta_note":"Useful for team-building insights."},
  {"id":"q070","text":"If you could swap two mundane tasks with someone, what would you trade and why?","tags":["fun","household"],"meta_note":"Light barter-thinking prompt."},
  {"id":"q071","text":"Tell a memory where music changed the meaning of a moment for you.","tags":["music","story"],"meta_note":"Sensory and emotional recall."},
  {"id":"q072","text":"What trivial controversy do you have a strong opinion about?","tags":["quirky","fun"],"meta_note":"Great for playful debates."},
  {"id":"q073","text":"If you could ask your future self one question, what would it be?","tags":["self","future"],"meta_note":"Future-oriented reflection."},
  {"id":"q074","text":"Describe a time a stranger challenged one of your assumptions.","tags":["learning","deep"],"meta_note":"Promotes openness and humility."},
  {"id":"q075","text":"What’s a ritual you use to mark the end of a meaningful chapter in life?","tags":["rituals","self"],"meta_note":"Closure and life transitions."},
  {"id":"q076","text":"If you could run a pop-up event, what would the theme be and who would you invite?","tags":["collaboration","community"],"meta_note":"Idea-generation for IRL connections."},
  {"id":"q077","text":"Tell a story about a small object that changed meaning over time.","tags":["story","nostalgia"],"meta_note":"Material culture narrative."},
  {"id":"q078","text":"What’s a belief you hold that would sound weird to people who don’t know you?","tags":["quirky","identity"],"meta_note":"Invites candid personality reveals."},
  {"id":"q079","text":"If you had to choose, would you prefer a year of stability or a year of wild change? Why?","tags":["values","self"],"meta_note":"Reveals risk appetite and life stage."},
  {"id":"q080","text":"Describe a small experiment you want to try in your relationships this month.","tags":["relationship","action"],"meta_note":"Encourages experimentation and micro-habits."},
  {"id":"q081","text":"What’s a question you use to test chemistry with someone new?","tags":["relationship","friends"],"meta_note":"Practical for dating or friendships."},
  {"id":"q082","text":"If you could ask society one uncomfortable question, what would it be?","tags":["intellectual","deep"],"meta_note":"Provocative civic prompt."},
  {"id":"q083","text":"Share a moment when silence spoke louder than words.","tags":["deep","relationship"],"meta_note":"Powerful for intimate groups."},
  {"id":"q084","text":"If you could design an afternoon workshop for curious people, what would people learn?","tags":["collaboration","learning"],"meta_note":"Useful for community activation."},
  {"id":"q085","text":"What's a small but meaningful compliment you can give someone right now?","tags":["friends","relationship"],"meta_note":"Encourages immediate kindness practice."},
  {"id":"q086","text":"Tell about a time a pattern in your life shifted and why it mattered.","tags":["self","growth"],"meta_note":"Narrative about transition."},
  {"id":"q087","text":"What would you ask to understand someone's worldview in five minutes?","tags":["friends","intellectual"],"meta_note":"Rapid-personality probe."},
  {"id":"q088","text":"If you could create a low-stakes challenge for your friend group, what would it be?","tags":["games","fun"],"meta_note":"For bonding and playful competition."},
  {"id":"q089","text":"Describe a time you felt both scared and excited—what did you do?","tags":["self","story"],"meta_note":"Explores ambivalence and action."},
  {"id":"q090","text":"What small change in language or phrase would make your relationships kinder?","tags":["relationship","communication"],"meta_note":"Practical communication tweak."},
  {"id":"q091","text":"If you could live a year in any fictional universe, which one and why?","tags":["fun","thought-experiment"],"meta_note":"Imaginative escape for groups."},
  {"id":"q092","text":"Share a tiny ritual for ending your day that actually works.","tags":["self","rituals"],"meta_note":"Exchange real habits people can try."},
  {"id":"q093","text":"What minor inconvenience would you happily accept for a big, meaningful payoff?","tags":["values","self"],"meta_note":"Reveals trade-offs and priorities."},
  {"id":"q094","text":"If you had to teach someone empathy in one hour, what exercise would you run?","tags":["collaboration","skills"],"meta_note":"Useful for facilitation design."},
  {"id":"q095","text":"Describe a moment when you were wrong and what you did about it.","tags":["self","growth"],"meta_note":"Models humility and repair."},
  {"id":"q096","text":"What's a counterfactual: how would your life be different if you’d never left your hometown?","tags":["counterfactual","story"],"meta_note":"Alternate-life exploration."},
  {"id":"q097","text":"What’s a playful boundary you set that actually improved a friendship?","tags":["friends","relationship"],"meta_note":"Normalizes boundaries with humour."},
  {"id":"q098","text":"If you could curate a three-item care package for a friend going through a rough week, what goes in it?","tags":["friends","care"],"meta_note":"Practical empathy prompt."},
  {"id":"q099","text":"Share a thought experiment you love to think about when you can’t sleep.","tags":["intellectual","thought-experiment"],"meta_note":"Great for late-night conversations."},
  {"id":"q100","text":"What’s a closing question you’d ask after a deep conversation to honour the moment?","tags":["relationship","rituals"],"meta_note":"Helps end intimacy gently and intentionally."}
]


[
  {"id":"q101","text":"If you could witness any historical moment in person, which would you choose and why?","tags":["intellectual","thought-experiment","self"],"meta_note":"Great for history buffs and values-based conversation."},
  {"id":"q102","text":"Describe a secret corner of your city few people know about—what makes it special?","tags":["friends","community","story"],"meta_note":"Local recommendations + sensory detail make answers vivid."},
  {"id":"q103","text":"What mundane skill do you think everyone should learn and why?","tags":["self","skills","practical"],"meta_note":"Reveals practical values and teaching moments."},
  {"id":"q104","text":"Imagine you swapped lives with your child/younger relative for a week — what would you learn?","tags":["family","counterfactual","self"],"meta_note":"Explores empathy across generations."},
  {"id":"q105","text":"If you had a personal museum, what three items would be displayed and what would each label say?","tags":["self","story","fun"],"meta_note":"Combines objects with identity and storytelling."},
  {"id":"q106","text":"What's a petty passion you secretly enjoy but rarely admit?","tags":["quirky","fun","self"],"meta_note":"Light, confessional, perfect for friendly groups."},
  {"id":"q107","text":"Which ethical trade-off do you think will define this century?","tags":["intellectual","deep","future"],"meta_note":"Good for debate and big-picture thinking."},
  {"id":"q108","text":"Describe a meal you’d cook to impress someone important to you—what are the flavors and the moment like?","tags":["relationship","sensory","friends"],"meta_note":"Easier to answer with concrete sensory cues."},
  {"id":"q109","text":"If you and a friend built a micro-business just for fun, what would it sell and why?","tags":["collaboration","creative","friends"],"meta_note":"Sparks low-risk entrepreneurial imagination."},
  {"id":"q110","text":"Tell a brief story of an awkward first meeting that later turned into a friendship.","tags":["friends","story","humour"],"meta_note":"Great for bonding through shared embarrassment."},
  {"id":"q111","text":"What counterintuitive habit improved your life more than expected?","tags":["self","quirky","growth"],"meta_note":"Promotes practical curiosity about routine."},
  {"id":"q112","text":"If technology could grant one emotional superpower, which would you pick and how would you use it?","tags":["thought-experiment","intellectual","future"],"meta_note":"Mixes ethics with imaginative scenarios."},
  {"id":"q113","text":"Describe a conversation that changed your mind about something important.","tags":["deep","self","learning"],"meta_note":"Shows openness and the process of change."},
  {"id":"q114","text":"What’s a compact daily ritual that signals you’re in love with your life?","tags":["rituals","self","relationship"],"meta_note":"Actionable, positive prompt for wellbeing."},
  {"id":"q115","text":"If you could ask a stranger one question and get a truthful answer, what would you ask?","tags":["friends","intellectual","curiosity"],"meta_note":"Great for exploring hidden social truths."},
  {"id":"q116","text":"Tell us about a creative failure that taught you more than success did.","tags":["collaboration","learning","story"],"meta_note":"Normalizes risk and iterating in creative work."},
  {"id":"q117","text":"Which season of the year best represents your personality right now and why?","tags":["self","metaphor","fun"],"meta_note":"Simple metaphor that reveals mood and tempo."},
  {"id":"q118","text":"If you could design a 'first-date' ritual that guarantees good conversation, what would it include?","tags":["relationship","games","practical"],"meta_note":"Useful for couples and dating features."},
  {"id":"q119","text":"What tiny change in your home would make it feel 50% more like you?","tags":["self","design","practical"],"meta_note":"Small, actionable home-improvement idea prompt."},
  {"id":"q120","text":"Describe an instance when silence between people felt productive rather than awkward.","tags":["relationship","deep","communication"],"meta_note":"Good for discussing intimacy and listening."},
  {"id":"q121","text":"If you could time-travel to give yourself one non-material gift, what would it be and why?","tags":["self","counterfactual","reflection"],"meta_note":"Encourages introspective priority-setting."},
  {"id":"q122","text":"What's a conspiracy theory (benign or silly) that you kind of enjoy imagining?","tags":["quirky","fun","culture"],"meta_note":"Light and playful; avoid harmful topics."},
  {"id":"q123","text":"Describe an ordinary kindness you witnessed that felt revolutionary.","tags":["friends","family","community"],"meta_note":"Encourages noticing small moral acts."},
  {"id":"q124","text":"If your friendships were a genre of music, which would they be and why?","tags":["friends","creative","metaphor"],"meta_note":"Metaphor-rich prompt to reveal social tone."},
  {"id":"q125","text":"What single question would you ask to judge whether someone is a good dinner companion?","tags":["friends","practical","conversation"],"meta_note":"Useful for screening and chemistry cues."},
  {"id":"q126","text":"Tell about a time you changed someone’s mind gently—what approach worked?","tags":["communication","deep","learning"],"meta_note":"Encourages civil persuasion techniques."},
  {"id":"q127","text":"If you had to build a three-step trust ritual between partners, what are the steps?","tags":["relationship","rituals","practical"],"meta_note":"Actionable rituals for relationship-building."},
  {"id":"q128","text":"Describe a book you’d assign to your future child and why.","tags":["family","values","story"],"meta_note":"Reveals long-term values and aspirations."},
  {"id":"q129","text":"What’s a facet of your personality that only your closest friends understand?","tags":["friends","identity","deep"],"meta_note":"Invites intimate self-description."},
  {"id":"q130","text":"If you could map a perfect week of work-life balance, what would the map look like?","tags":["self","work","practical"],"meta_note":"Good for productivity and wellbeing discussion."},
  {"id":"q131","text":"Share a spontaneous act you did that brought unexpected joy.","tags":["fun","friends","story"],"meta_note":"Promotes risk-taking for delight."},
  {"id":"q132","text":"If you could pick one small thing to teach everyone in your city, what would it be?","tags":["community","skills","collaboration"],"meta_note":"Civic improvement and skill-sharing prompt."},
  {"id":"q133","text":"Describe a habit you adopted from someone you admire and how it changed you.","tags":["self","role-model","growth"],"meta_note":"Explores social learning and mentorship."},
  {"id":"q134","text":"If your life were a board game, what would the win condition be?","tags":["fun","creative","metaphor"],"meta_note":"Game-design metaphor for values and goals."},
  {"id":"q135","text":"Tell a short counterfactual: if you’d grown up in a different country, which parts of you would be different?","tags":["counterfactual","identity","deep"],"meta_note":"Explores cultural shaping and identity."},
  {"id":"q136","text":"What’s one ethical consumer choice you struggle with and why?","tags":["intellectual","values","practical"],"meta_note":"Invites honest, nuanced answers about trade-offs."},
  {"id":"q137","text":"Describe a tiny moment someone made you believe in serendipity.","tags":["friends","story","magic"],"meta_note":"Warm storytelling prompt to build wonder."},
  {"id":"q138","text":"If you had to keep only five apps on your phone, which would survive and why?","tags":["tech","personal","practical"],"meta_note":"Reveals priorities and digital minimalism."},
  {"id":"q139","text":"What question would you ask to know whether a new coworker will be a cultural fit?","tags":["collaboration","work","practical"],"meta_note":"Useful for hiring and team dynamics."},
  {"id":"q140","text":"Tell about a time when changing a small word in a conversation shifted the whole outcome.","tags":["communication","self","learning"],"meta_note":"Power of language and framing."},
  {"id":"q141","text":"If you could invent a new holiday to bring people closer, what traditions would it include?","tags":["community","rituals","creative"],"meta_note":"Group-creative prompt with practical rituals."},
  {"id":"q142","text":"Describe a childhood game you think more adults should play and why.","tags":["fun","nostalgia","friends"],"meta_note":"Encourages playfulness and intergenerational ideas."},
  {"id":"q143","text":"What’s a simple practice that helps you recover after an argument?","tags":["relationship","self","repair"],"meta_note":"Concrete conflict-repair strategies."},
  {"id":"q144","text":"If you could build an ideal co-working space for creative people, what would the vibe be?","tags":["collaboration","design","community"],"meta_note":"Product and community design prompt."},
  {"id":"q145","text":"Describe a time you used boredom productively—what did you create or think about?","tags":["self","creativity","growth"],"meta_note":"Reframes boredom as generative."},
  {"id":"q146","text":"If you could teach strangers one question to start better conversations, what would it be?","tags":["friends","conversation","practical"],"meta_note":"Meta-conversation tool for social skill building."},
  {"id":"q147","text":"Tell a short story about a ritual you inherited and kept, even if it seemed odd.","tags":["family","rituals","story"],"meta_note":"Explores tradition and continuity."},
  {"id":"q148","text":"What fictional technology would you welcome into real life, and how would it change relationships?","tags":["thought-experiment","future","relationship"],"meta_note":"Speculative, great for imaginative debates."},
  {"id":"q149","text":"Name a small question you ask on dates to avoid small-talk and get real quickly.","tags":["relationship","practical","conversation"],"meta_note":"Dating-proven icebreaker prompt."},
  {"id":"q150","text":"If you could choose a sound to represent your happiest memory, what would it be?","tags":["sensory","self","nostalgia"],"meta_note":"Sensory recall that evokes vivid description."},
  {"id":"q151","text":"Describe a time you stewarded someone else's trust—what did that teach you?","tags":["deep","relationship","ethics"],"meta_note":"Conversation about responsibility and care."},
  {"id":"q152","text":"If you could make one small city regulation friendlier, which would it be and why?","tags":["community","practical","collaboration"],"meta_note":"Local policy + empathy prompt for civic design."},
  {"id":"q153","text":"What's a petty annoyance that makes you unexpectedly creative?","tags":["quirky","creativity","self"],"meta_note":"Humorous and revealing about creative processes."},
  {"id":"q154","text":"Tell a story about the last time you changed plans and discovered something better.","tags":["friends","story","flexibility"],"meta_note":"Encourages adaptability and serendipity."},
  {"id":"q155","text":"If you were writing your 'ideal friend' ad, what are the three must-have lines?","tags":["friends","creative","practical"],"meta_note":"Helps people articulate social needs."},
  {"id":"q156","text":"Describe a cultural ritual you admire from another country and why it moves you.","tags":["culture","deep","learning"],"meta_note":"Cross-cultural empathy prompt."},
  {"id":"q157","text":"What tiny sound, sight, or smell immediately transports you back to a childhood memory?","tags":["sensory","nostalgia","self"],"meta_note":"Powerful sensory memory trigger for deep sharing."},
  {"id":"q158","text":"If you could create a 10-minute unplugged ritual for your team before meetings, what would it be?","tags":["collaboration","work","rituals"],"meta_note":"Builds calmer, more focused team culture."},
  {"id":"q159","text":"Tell about a time you received advice you didn't follow—and what happened next.","tags":["self","story","growth"],"meta_note":"Examines autonomy and consequences."},
  {"id":"q160","text":"If you had to create a two-question personality test to pick travel companions, what are the questions?","tags":["friends","travel","practical"],"meta_note":"Useful for trip planning and compatibility screening."},
  {"id":"q161","text":"What's a small productivity ritual that actually feels luxurious to you?","tags":["self","productivity","rituals"],"meta_note":"Mixes wellbeing and efficiency in a human way."},
  {"id":"q162","text":"If you could swap one modern convenience for a slower ritual, what would you trade?","tags":["counterfactual","self","lifestyle"],"meta_note":"Explores pace and intentional living trade-offs."},
  {"id":"q163","text":"Describe a time humor healed an awkward or tense situation.","tags":["friends","communication","fun"],"meta_note":"Shows the social utility of levity and timing."},
  {"id":"q164","text":"If you had to pick a single question that reveals someone's curiosity, what is it?","tags":["intellectual","friends","conversation"],"meta_note":"Helps identify inquisitive conversationalists quickly."},
  {"id":"q165","text":"Tell a short story about a small object you lost and what that loss felt like.","tags":["nostalgia","story","self"],"meta_note":"Explores attachment and meaning-making."},
  {"id":"q166","text":"What micro-adventure could you plan this weekend with minimal cost and high joy?","tags":["friends","fun","practical"],"meta_note":"Actionable adventure prompts to spark immediate plans."},
  {"id":"q167","text":"If you were to write a postcard to your future partner, what three words would you write on the front?","tags":["relationship","creative","romantic"],"meta_note":"Tiny poetic prompt for romantic imagination."},
  {"id":"q168","text":"Describe a time a stranger's small comment changed your day for the better.","tags":["community","kindness","story"],"meta_note":"Shows social ripple effects of small acts."},
  {"id":"q169","text":"What obscure skill would you like to learn just because it seems fun?","tags":["creative","self","quirky"],"meta_note":"Encourages playful lifelong learning."},
  {"id":"q170","text":"If you could pose one question to your workplace to make it kinder, what would it be?","tags":["work","collaboration","values"],"meta_note":"Prompt for organizational reflection and improvement."},
  {"id":"q171","text":"Tell about a time you noticed someone else's courage and how you responded.","tags":["friends","deep","care"],"meta_note":"Conversation about witnessing and supporting bravery."},
  {"id":"q172","text":"If you could craft a one-sentence ritual for ending arguments, what would it be?","tags":["relationship","communication","rituals"],"meta_note":"Practical, calming language for conflict resolution."},
  {"id":"q173","text":"What imaginary tradition would you like to found for your friend group?","tags":["friends","creative","rituals"],"meta_note":"Group-building prompt to create belonging rituals."},
  {"id":"q174","text":"Describe a time when changing your environment helped you solve a problem.","tags":["work","self","story"],"meta_note":"Illustrates context-dependent creativity."},
  {"id":"q175","text":"If you could ask one question to measure someone's generosity, what would it be?","tags":["values","friends","deep"],"meta_note":"Reveals moral imagination and priorities."},
  {"id":"q176","text":"Share a small act of rebelliousness that felt liberating.","tags":["quirky","self","story"],"meta_note":"Playful prompt about constraint and freedom."},
  {"id":"q177","text":"What fictional mentor would you want guiding your career, and what would they advise?","tags":["creative","career","fun"],"meta_note":"Combines mentorship with imaginative role models."},
  {"id":"q178","text":"Tell about a time you created something with a friend that taught you about cooperation.","tags":["collaboration","friends","learning"],"meta_note":"Explores team dynamics in small projects."},
  {"id":"q179","text":"If you could translate one private feeling into a public policy, what would it prioritize?","tags":["intellectual","community","values"],"meta_note":"For civic imagination and moral debate."},
  {"id":"q180","text":"Describe the worst piece of advice you once got and what you replaced it with.","tags":["self","learning","humour"],"meta_note":"Encourages critical reflection on received wisdom."},
  {"id":"q181","text":"If you had to teach someone your cultural background in one hour, what would you include?","tags":["culture","family","education"],"meta_note":"Compact cultural introduction exercise."},
  {"id":"q182","text":"What small ritual helps you move from 'work mode' to 'present mode' at home?","tags":["rituals","self","work"],"meta_note":"Practical transition ritual for wellbeing."},
  {"id":"q183","text":"Tell a story about the most unexpectedly generous collaboration you’ve experienced.","tags":["collaboration","story","gratitude"],"meta_note":"Builds trust through positive examples."},
  {"id":"q184","text":"If you could steal one habit from another person in this room, what would it be and why?","tags":["friends","fun","growth"],"meta_note":"Playful, immediate swap exercise for groups."},
  {"id":"q185","text":"Describe a time you felt small in a good way—overwhelmed by beauty or wonder.","tags":["self","spiritual","story"],"meta_note":"Elevates awe and transcendence in conversation."},
  {"id":"q186","text":"If your life had a mascot, what would it be and what quirks would it have?","tags":["creative","fun","self"],"meta_note":"Whimsical prompt to externalize personality."},
  {"id":"q187","text":"What’s one small boundary you wish more people respected, and how do you communicate it?","tags":["relationship","communication","practical"],"meta_note":"Encourages boundary-setting examples."},
  {"id":"q188","text":"Tell a counterfactual: what if kindness was the default social currency—how would daily life change?","tags":["counterfactual","community","values"],"meta_note":"Speculative civic design to inspire real change ideas."},
  {"id":"q189","text":"Describe a time when a tiny tweak in a project unlocked momentum.","tags":["collaboration","work","process"],"meta_note":"Shareable lessons on small leverage points."},
  {"id":"q190","text":"If you had to invent an icebreaker that avoids small talk, what’s your go-to prompt?","tags":["friends","games","conversation"],"meta_note":"Useful for facilitators and hosts."},
  {"id":"q191","text":"What outfit or item makes you feel most like yourself and why?","tags":["self","identity","sensory"],"meta_note":"Material identity + sensory storytelling."},
  {"id":"q192","text":"Tell a story about a time you misread a situation—what did you learn?","tags":["learning","humour","self"],"meta_note":"Models humility and interpretive fallibility."},
  {"id":"q193","text":"If you could plant a symbolic tree representing your life today, what kind would it be and where would it grow?","tags":["metaphor","self","future"],"meta_note":"Poetic, grounding prompt for reflection."},
  {"id":"q194","text":"What small innovation would make family gatherings less stressful and more joyful?","tags":["family","practical","community"],"meta_note":"Actionable, empathy-focused family solutions."},
  {"id":"q195","text":"Describe a time you deliberately slowed down—what did you notice that you’d missed before?","tags":["mindfulness","self","story"],"meta_note":"Encourages noticing and savoring practices."},
  {"id":"q196","text":"If you could ask your best friend to describe you in three honest words, what do you hope they’d pick?","tags":["friends","self","values"],"meta_note":"Reflective check-in that surfaces self-image vs. social image."},
  {"id":"q197","text":"Tell a short story about a creative constraint that led to a breakthrough.","tags":["creativity","collaboration","work"],"meta_note":"Demonstrates how limits can fuel invention."},
  {"id":"q198","text":"If your next conversation had to include an element of play, what would you add?","tags":["games","friends","fun"],"meta_note":"Encourages playful scaffolding for richer chats."},
  {"id":"q199","text":"Describe a small tradition you’d like to inherit or pass on—how would it look in practice?","tags":["family","rituals","values"],"meta_note":"Intergenerational continuity and ritual design."},
  {"id":"q200","text":"What's a personal rule you apply when making difficult decisions?","tags":["self","ethics","decision-making"],"meta_note":"Reveals decision heuristics and moral frames."},
  {"id":"q201","text":"If you could have coffee with your favourite author, what’s the first awkward question you’d ask?","tags":["intellectual","fun","books"],"meta_note":"Mix of admiration and curiosity—great literary prompt."},
  {"id":"q202","text":"Tell a brief story of a time you witnessed someone defending something quietly but powerfully.","tags":["deep","community","story"],"meta_note":"Highlights moral courage in subtle forms."},
  {"id":"q203","text":"If you could add one small practice to your morning routine that guaranteed better relationships, what would it be?","tags":["relationship","rituals","self"],"meta_note":"Practical, tiny habit ideas for relational health."},
  {"id":"q204","text":"Describe a moment when you learned to listen rather than respond—what changed?","tags":["communication","self","growth"],"meta_note":"Active listening and its transformative power."},
  {"id":"q205","text":"What's an unconventional place you'd host a conversation salon and why?","tags":["community","creative","events"],"meta_note":"Sparks offbeat location-based social experiments."},
  {"id":"q206","text":"If you could compress your life's lessons into a short podcast episode, what would its title be?","tags":["story","self","creative"],"meta_note":"Meta reflection packaged as a creative product."},
  {"id":"q207","text":"Tell about a time you made peace with a small failure—how did you reframe it?","tags":["growth","self","resilience"],"meta_note":"Models cognitive reframing for resilience."},
  {"id":"q208","text":"If you could ask your partner one question that guarantees a meaningful answer, what would it be?","tags":["relationship","practical","deep"],"meta_note":"Designed for intimacy and clarity in relationships."},
  {"id":"q209","text":"Describe a small experiment you ran to improve a friendship—what worked and what didn't?","tags":["friends","collaboration","learning"],"meta_note":"Actionable social science: iterate on friendships."},
  {"id":"q210","text":"What's a minor inconvenience you'd happily live with to gain a big emotional benefit?","tags":["values","self","tradeoffs"],"meta_note":"Explores personal trade-off boundaries."},
  {"id":"q211","text":"If you could write a one-paragraph obituary for your work-life balance, what would it praise?","tags":["work","self","values"],"meta_note":"Provocative future-self exercise for priorities."},
  {"id":"q212","text":"Tell a short anecdote about a time you miscommunicated and the surprising positive outcome.","tags":["communication","friends","story"],"meta_note":"Highlights repair and unexpected blessings."},
  {"id":"q213","text":"If you had to pick a five-question survey to understand someone's emotional health, what are the questions?","tags":["collaboration","self","care"],"meta_note":"Practical for building empathetic check-ins."},
  {"id":"q214","text":"Describe a hobby you tried that made you feel foolish at first—what kept you going?","tags":["creativity","self","learning"],"meta_note":"Encourages vulnerability and perseverance."},
  {"id":"q215","text":"If you could host a month-long exchange with any cultural group, which would you choose and what would you hope to learn?","tags":["culture","deep","learning"],"meta_note":"Cross-cultural curiosity and deep listening prompt."},
  {"id":"q216","text":"What's a small phrase you use to show appreciation that never gets old?","tags":["gratitude","relationship","practical"],"meta_note":"Practical language to strengthen relationships."},
  {"id":"q217","text":"Tell a story about a time you found beauty in an unexpected place.","tags":["awe","story","self"],"meta_note":"Promotes noticing and gratitude practices."},
  {"id":"q218","text":"If you could compress your favorite philosophical idea into a 20-second elevator pitch, what would it be?","tags":["intellectual","philosophy","creative"],"meta_note":"Sharp thinking exercise to clarify big ideas."},
  {"id":"q219","text":"Describe a time you gave someone space when they needed it—what was the outcome?","tags":["relationship","care","communication"],"meta_note":"Shows nuanced care and respect for autonomy."},
  {"id":"q220","text":"If you could make one small change to how your city celebrates community, what would you propose?","tags":["community","collaboration","ideas"],"meta_note":"Civic design prompt with immediate local impact."},
  {"id":"q221","text":"What's a question you'd ask to understand someone's childhood in five minutes?","tags":["family","deep","conversation"],"meta_note":"Rapid family-history probe to reveal formative contexts."},
  {"id":"q222","text":"Tell about a time you resisted an easy path and chose the harder, better option.","tags":["self","values","story"],"meta_note":"Shows moral courage and integrity in small choices."},
  {"id":"q223","text":"If you could invent a micro-ritual to start meetings that increases empathy, what would it be?","tags":["work","collaboration","rituals"],"meta_note":"Team practices for kinder meetings."},
  {"id":"q224","text":"Describe an example of 'productive boredom' you experienced—what emerged?","tags":["creativity","self","process"],"meta_note":"Encourages incubation and idea-generation techniques."},
  {"id":"q225","text":"If you could translate one personal failure into a lesson to teach others, what would it be?","tags":["self","learning","story"],"meta_note":"Shareable wisdom distilled from experience."},
  {"id":"q226","text":"What's a small neighborly act that would radically improve your block?","tags":["community","practical","care"],"meta_note":"Local change ideas that build cohesion."},
  {"id":"q227","text":"Tell a brief story about a time you used play to solve a serious problem.","tags":["games","collaboration","creativity"],"meta_note":"Demonstrates playful problem-solving efficacy."},
  {"id":"q228","text":"If you could pick an annual theme word for your life next year, what would it be and why?","tags":["self","goals","reflection"],"meta_note":"Simple framing device for intentional living."},
  {"id":"q229","text":"Describe a time you resisted giving advice and instead listened—what happened?","tags":["communication","deep","care"],"meta_note":"Models wise empathy and presence."},
  {"id":"q230","text":"If your closest friends made a mixtape for you, what three songs would you hope are on it and why?","tags":["friends","music","nostalgia"],"meta_note":"Evokes social soundtracks and emotional associations."},
  {"id":"q231","text":"Tell about a small piece of community infrastructure you'd build tomorrow if you had funding.","tags":["community","collaboration","ideas"],"meta_note":"Practical civic innovation prompt."},
  {"id":"q232","text":"What's a private rule you follow that makes public life easier?","tags":["self","ethics","practical"],"meta_note":"Operational life-hacks that scale socially."},
  {"id":"q233","text":"If you could choose one question to make awkward conversations productive, what would it be?","tags":["communication","friends","practical"],"meta_note":"Conflict-transformation starter for honest talks."},
  {"id":"q234","text":"Describe a time when a small token (note, object, song) repaired a fragile relationship.","tags":["relationship","story","repair"],"meta_note":"Shows reparative gestures and their potency."},
  {"id":"q235","text":"If you could host an ‘improv empathy’ evening, what prompt would you give participants?","tags":["games","community","skills"],"meta_note":"Interactive empathy-building exercise for groups."},
  {"id":"q236","text":"Tell a story of a moment you felt unexpectedly brave—what did bravery look like?","tags":["deep","self","story"],"meta_note":"Personal courage narratives encourage reciprocity."},
  {"id":"q237","text":"What's a small tradition you’d embed into your wedding or partnership ceremony to keep conversation alive afterward?","tags":["relationship","rituals","future"],"meta_note":"Practical long-term relationship design idea."},
  {"id":"q238","text":"Describe an instance where you noticed your privilege and how you responded.","tags":["values","deep","reflection"],"meta_note":"Confrontational but necessary for growth—use with care."},
  {"id":"q239","text":"If you could time-box a monthly creativity hour for your friend group, what would you do?","tags":["friends","creativity","rituals"],"meta_note":"Scaffold for recurring collaborative play."},
  {"id":"q240","text":"Tell about a small moment of reconciliation you witnessed that inspired you.","tags":["community","story","care"],"meta_note":"Highlights restorative practices and hope."},
  {"id":"q241","text":"If you could invent a mini-game to test emotional honesty, how would it work?","tags":["games","relationship","psychology"],"meta_note":"Design prompt merging play with depth."},
  {"id":"q242","text":"Describe the most unusual compliment you've given someone and their reaction.","tags":["fun","friends","social"],"meta_note":"Explores creative praise and its social effects."},
  {"id":"q243","text":"What would you add to your hometown to make it a place you'd raise a child in?","tags":["community","future","family"],"meta_note":"Visionary prompt for urban improvements."},
  {"id":"q244","text":"Tell about a time you were surprised by how resilient you were.","tags":["resilience","self","story"],"meta_note":"Strength-focused recollection that builds confidence."},
  {"id":"q245","text":"If you could design a 'slow first date' itinerary, what are the three stops?","tags":["relationship","creative","practical"],"meta_note":"Promotes extended-encounter dating rather than speed dating."},
  {"id":"q246","text":"Describe a habit you dropped that turned out to be a liberation.","tags":["self","growth","story"],"meta_note":"Stories of relinquishment and freedom."},
  {"id":"q247","text":"If you were to curate a small museum of ordinary objects, what theme would you pick and why?","tags":["creative","story","curation"],"meta_note":"Curatorial imagination fused with personal taste."},
  {"id":"q248","text":"Tell about a time you chose curiosity over judgment—what difference did it make?","tags":["learning","deep","communication"],"meta_note":"Promotes nonjudgmental inquiry as a social skill."},
  {"id":"q249","text":"If you had to explain love to an alien in three sentences, what would you say?","tags":["creative","relationship","philosophy"],"meta_note":"Stripped-down, imaginative definition exercise."},
  {"id":"q250","text":"Describe one small, testable promise you could make to a friend to strengthen your bond this month.","tags":["friends","actionable","relationship"],"meta_note":"Concrete micro-commitment to build reliability and trust."}
]
